apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: zakyfatih/python-program:14
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30005
